/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetRFL;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Scanner;

/**
 *
 * @author Stefan
 */
public class AffichageParamètresEmployé extends javax.swing.JFrame {

    public void AffichageEmployé() throws FileNotFoundException{
        
    Scanner in = new Scanner(new FileReader("ID.txt"));
    StringBuilder sb = new StringBuilder();
        while(in.hasNext()) {
            sb.append(in.next());
        }
    in.close();
    String id = sb.toString();
    String str="SELECT * FROM Employé WHERE ID='" + id + "'";
        Connection con = null;
    try{

            con = DriverManager.getConnection("jdbc:mysql://localhost:8889/BDD-Vols", "root", "root");

            Statement stm;
           
            stm = con.createStatement();

            ResultSet rst = stm.executeQuery(str);

           if(rst.next())
            {
                AffichageNomEmployé.setText(rst.getString("Nom"));
                AffichagePrénomEmployé.setText(rst.getString("Prenom"));
                AffichageMailEmployé.setText(rst.getString("Email"));
            }
            else{
                    new ErreurModificationParamètres().setVisible(true);
                }
        }catch (Exception e) 
        {
            e.printStackTrace();
        }
    }
    /**
     * Creates new form AffichageParamètresEmployé
     */
    public AffichageParamètresEmployé() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        BoutonRetourAffichageParamètresEmployé = new javax.swing.JButton();
        TitreAffichageParamètresEmployé = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        TitreNomAffichageParamètresEmployé = new javax.swing.JLabel();
        AffichageNomEmployé = new javax.swing.JLabel();
        TitrePrénomAffichageParamètresEmployé = new javax.swing.JLabel();
        AffichagePrénomEmployé = new javax.swing.JLabel();
        TitreMailAffichageParamètresEmployé = new javax.swing.JLabel();
        AffichageMailEmployé = new javax.swing.JLabel();
        TitreMailAffichageParamètresEmployé1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        BoutonEnregistrerModifParam1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paramètres du compte");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        BoutonRetourAffichageParamètresEmployé.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        BoutonRetourAffichageParamètresEmployé.setText("Précédent");
        BoutonRetourAffichageParamètresEmployé.setBorder(null);
        BoutonRetourAffichageParamètresEmployé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRetourAffichageParamètresEmployéActionPerformed(evt);
            }
        });

        TitreAffichageParamètresEmployé.setBackground(new java.awt.Color(255, 255, 255));
        TitreAffichageParamètresEmployé.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        TitreAffichageParamètresEmployé.setText("Paramètres du compte");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoutonRetourAffichageParamètresEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1009, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addContainerGap(340, Short.MAX_VALUE)
                    .addComponent(TitreAffichageParamètresEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoutonRetourAffichageParamètresEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TitreAffichageParamètresEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1140, 60));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        TitreNomAffichageParamètresEmployé.setBackground(new java.awt.Color(255, 255, 255));
        TitreNomAffichageParamètresEmployé.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        TitreNomAffichageParamètresEmployé.setText("Nom :");

        AffichageNomEmployé.setBackground(new java.awt.Color(255, 255, 255));
        AffichageNomEmployé.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N

        TitrePrénomAffichageParamètresEmployé.setBackground(new java.awt.Color(255, 255, 255));
        TitrePrénomAffichageParamètresEmployé.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        TitrePrénomAffichageParamètresEmployé.setText("Prénom :");

        AffichagePrénomEmployé.setBackground(new java.awt.Color(255, 255, 255));
        AffichagePrénomEmployé.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N

        TitreMailAffichageParamètresEmployé.setBackground(new java.awt.Color(255, 255, 255));
        TitreMailAffichageParamètresEmployé.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        TitreMailAffichageParamètresEmployé.setText("Addresse mail :");

        AffichageMailEmployé.setBackground(new java.awt.Color(255, 255, 255));
        AffichageMailEmployé.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N

        TitreMailAffichageParamètresEmployé1.setBackground(new java.awt.Color(255, 255, 255));
        TitreMailAffichageParamètresEmployé1.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        TitreMailAffichageParamètresEmployé1.setText("Rentrez votre MDP :");

        jPasswordField1.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        BoutonEnregistrerModifParam1.setBackground(new java.awt.Color(0, 194, 90));
        BoutonEnregistrerModifParam1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        BoutonEnregistrerModifParam1.setForeground(new java.awt.Color(255, 255, 255));
        BoutonEnregistrerModifParam1.setText("Valider");
        BoutonEnregistrerModifParam1.setBorder(null);
        BoutonEnregistrerModifParam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonEnregistrerModifParam1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TitreMailAffichageParamètresEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitrePrénomAffichageParamètresEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitreNomAffichageParamètresEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AffichageMailEmployé, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(AffichagePrénomEmployé, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AffichageNomEmployé, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(TitreMailAffichageParamètresEmployé1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoutonEnregistrerModifParam1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TitreMailAffichageParamètresEmployé1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoutonEnregistrerModifParam1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(TitreNomAffichageParamètresEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AffichageNomEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TitrePrénomAffichageParamètresEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AffichagePrénomEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TitreMailAffichageParamètresEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AffichageMailEmployé, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 1130, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjetRFL/Template_bis copy.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonRetourAffichageParamètresEmployéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRetourAffichageParamètresEmployéActionPerformed
        new ParamètresEmployé().setVisible(true);
        dispose();
    }//GEN-LAST:event_BoutonRetourAffichageParamètresEmployéActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void BoutonEnregistrerModifParam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonEnregistrerModifParam1ActionPerformed
        
        String str="SELECT * FROM Employé WHERE Mdp='" + jPasswordField1.getText() + "'";
        Connection con = null;
    try{

            con = DriverManager.getConnection("jdbc:mysql://localhost:8889/BDD-Vols", "root", "root");

            Statement stm;
           
            stm = con.createStatement();

            ResultSet rst = stm.executeQuery(str);

           if(rst.next())
            {
                AffichageNomEmployé.setText(rst.getString("Nom"));
                AffichagePrénomEmployé.setText(rst.getString("Prenom"));
                AffichageMailEmployé.setText(rst.getString("Email"));
            }
            else{
                    new ErreurModificationParamètres().setVisible(true);
                }
        }catch (Exception e) 
        {
            e.printStackTrace();
        }
        dispose();
    }//GEN-LAST:event_BoutonEnregistrerModifParam1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffichageParamètresEmployé.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffichageParamètresEmployé.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffichageParamètresEmployé.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffichageParamètresEmployé.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AffichageParamètresEmployé().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel AffichageMailEmployé;
    javax.swing.JLabel AffichageNomEmployé;
    javax.swing.JLabel AffichagePrénomEmployé;
    private javax.swing.JButton BoutonEnregistrerModifParam1;
    private javax.swing.JButton BoutonRetourAffichageParamètresEmployé;
    private javax.swing.JLabel TitreAffichageParamètresEmployé;
    private javax.swing.JLabel TitreMailAffichageParamètresEmployé;
    private javax.swing.JLabel TitreMailAffichageParamètresEmployé1;
    private javax.swing.JLabel TitreNomAffichageParamètresEmployé;
    private javax.swing.JLabel TitrePrénomAffichageParamètresEmployé;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
