/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetRFL;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Stefan
 */
public class AffichageParamètres extends javax.swing.JFrame {

     public  void AffichageClient() throws FileNotFoundException{
        
    int i;
    String line = new String();
    
    try {
      //lire le fichier file.txt
      FileReader file = new FileReader("ID.txt");
      BufferedReader buffer = new BufferedReader(file);
    
      // parcourir le fichier
      for (i = 1; i < 10; i++) {
        // Si le numéro de la ligne = 5 récupérer la ligne
        if (i == 5)
          line = buffer.readLine();
        else
          buffer.readLine();
      }
    } catch (IOException e) {
      e.printStackTrace();
    }
    String id = line;
    String str="SELECT * FROM Employé WHERE ID='" + id + "'";
        Connection con = null;
    try{

            con = DriverManager.getConnection("jdbc:mysql://localhost:8889/BDD-Vols", "root", "root");

            Statement stm;
           
            stm = con.createStatement();

            ResultSet rst = stm.executeQuery(str);

           if(rst.next())
            {
                AffichageNom.setText(rst.getString("m_nom"));
                AffichagePrénom.setText(rst.getString("m_prenom"));
                AffichageMail.setText(rst.getString("m_email"));
                AffichageÂge.setText(rst.getString("m_age"));
                AffichageStatut.setText(rst.getString("m_statut"));
                AffichageVolsEffectués.setText(rst.getString("m_vols_effectues"));
                
                
                
            }
            else{
                    new Paramètres().setVisible(true);
                }
        }catch (Exception e) 
        {
            e.printStackTrace();
        }
    }
    /**
     * Creates new form AffichageParamètres
     */
    public AffichageParamètres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        BoutonRetourAffichageParamètres = new javax.swing.JButton();
        TitreAffichageParamètres = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        TitreNomAffichageParamètres = new javax.swing.JLabel();
        AffichageNom = new javax.swing.JLabel();
        TitrePrénomAffichageParamètres = new javax.swing.JLabel();
        AffichagePrénom = new javax.swing.JLabel();
        TitreAgeAffichageParamètres = new javax.swing.JLabel();
        AffichageÂge = new javax.swing.JLabel();
        TitreStatutAffichageParamètres = new javax.swing.JLabel();
        AffichageStatut = new javax.swing.JLabel();
        TitreMailAffichageParamètres = new javax.swing.JLabel();
        AffichageMail = new javax.swing.JLabel();
        TitreVolsEffectuésAffichageParamètres = new javax.swing.JLabel();
        AffichageVolsEffectués = new javax.swing.JLabel();
        TitreMailAffichageParamètresEmployé1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        BoutonEnregistrerModifParam2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paramètres du compte");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        BoutonRetourAffichageParamètres.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        BoutonRetourAffichageParamètres.setForeground(new java.awt.Color(38, 70, 148));
        BoutonRetourAffichageParamètres.setText("Précédent");
        BoutonRetourAffichageParamètres.setBorder(null);
        BoutonRetourAffichageParamètres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRetourAffichageParamètresActionPerformed(evt);
            }
        });

        TitreAffichageParamètres.setBackground(new java.awt.Color(255, 255, 255));
        TitreAffichageParamètres.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        TitreAffichageParamètres.setForeground(new java.awt.Color(38, 70, 148));
        TitreAffichageParamètres.setText("Paramètres du compte");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoutonRetourAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1009, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addContainerGap(340, Short.MAX_VALUE)
                    .addComponent(TitreAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(223, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoutonRetourAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TitreAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1140, 60));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        TitreNomAffichageParamètres.setBackground(new java.awt.Color(255, 255, 255));
        TitreNomAffichageParamètres.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        TitreNomAffichageParamètres.setForeground(new java.awt.Color(38, 70, 148));
        TitreNomAffichageParamètres.setText("Nom :");

        AffichageNom.setBackground(new java.awt.Color(255, 255, 255));
        AffichageNom.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N

        TitrePrénomAffichageParamètres.setBackground(new java.awt.Color(255, 255, 255));
        TitrePrénomAffichageParamètres.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        TitrePrénomAffichageParamètres.setForeground(new java.awt.Color(38, 70, 148));
        TitrePrénomAffichageParamètres.setText("Prénom :");

        AffichagePrénom.setBackground(new java.awt.Color(255, 255, 255));
        AffichagePrénom.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N

        TitreAgeAffichageParamètres.setBackground(new java.awt.Color(255, 255, 255));
        TitreAgeAffichageParamètres.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        TitreAgeAffichageParamètres.setForeground(new java.awt.Color(38, 70, 148));
        TitreAgeAffichageParamètres.setText("Âge :");

        AffichageÂge.setBackground(new java.awt.Color(255, 255, 255));
        AffichageÂge.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N

        TitreStatutAffichageParamètres.setBackground(new java.awt.Color(255, 255, 255));
        TitreStatutAffichageParamètres.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        TitreStatutAffichageParamètres.setForeground(new java.awt.Color(38, 70, 148));
        TitreStatutAffichageParamètres.setText("Statut :");

        AffichageStatut.setBackground(new java.awt.Color(255, 255, 255));
        AffichageStatut.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N

        TitreMailAffichageParamètres.setBackground(new java.awt.Color(255, 255, 255));
        TitreMailAffichageParamètres.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        TitreMailAffichageParamètres.setForeground(new java.awt.Color(38, 70, 148));
        TitreMailAffichageParamètres.setText("Addresse mail :");

        AffichageMail.setBackground(new java.awt.Color(255, 255, 255));
        AffichageMail.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N

        TitreVolsEffectuésAffichageParamètres.setBackground(new java.awt.Color(255, 255, 255));
        TitreVolsEffectuésAffichageParamètres.setFont(new java.awt.Font("MS UI Gothic", 3, 16)); // NOI18N
        TitreVolsEffectuésAffichageParamètres.setForeground(new java.awt.Color(38, 70, 148));
        TitreVolsEffectuésAffichageParamètres.setText("Nombre de vols effectués :");

        AffichageVolsEffectués.setBackground(new java.awt.Color(255, 255, 255));
        AffichageVolsEffectués.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N

        TitreMailAffichageParamètresEmployé1.setBackground(new java.awt.Color(255, 255, 255));
        TitreMailAffichageParamètresEmployé1.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        TitreMailAffichageParamètresEmployé1.setText("Rentrez votre MDP :");

        jPasswordField1.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        BoutonEnregistrerModifParam2.setBackground(new java.awt.Color(0, 194, 90));
        BoutonEnregistrerModifParam2.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        BoutonEnregistrerModifParam2.setForeground(new java.awt.Color(255, 255, 255));
        BoutonEnregistrerModifParam2.setText("Valider");
        BoutonEnregistrerModifParam2.setBorder(null);
        BoutonEnregistrerModifParam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonEnregistrerModifParam2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitreNomAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AffichageNom, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(190, 190, 190)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AffichagePrénom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TitrePrénomAffichageParamètres, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TitreAgeAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(AffichageÂge, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AffichageStatut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TitreStatutAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(270, 270, 270)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitreMailAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AffichageMail, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(169, 169, 169)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(AffichageVolsEffectués, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TitreVolsEffectuésAffichageParamètres, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitreMailAffichageParamètresEmployé1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoutonEnregistrerModifParam2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitreMailAffichageParamètresEmployé1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoutonEnregistrerModifParam2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(TitreAgeAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AffichageÂge, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(TitrePrénomAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AffichagePrénom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(TitreNomAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AffichageNom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(TitreVolsEffectuésAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AffichageVolsEffectués, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(TitreMailAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AffichageMail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(TitreStatutAffichageParamètres, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AffichageStatut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 1130, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjetRFL/Template_bis.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonRetourAffichageParamètresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRetourAffichageParamètresActionPerformed
        new Paramètres().setVisible(true);
        dispose();
    }//GEN-LAST:event_BoutonRetourAffichageParamètresActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void BoutonEnregistrerModifParam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonEnregistrerModifParam2ActionPerformed

         try {
             AffichageClient();
         } catch (FileNotFoundException ex) {
             Logger.getLogger(AffichageParamètres.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_BoutonEnregistrerModifParam2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffichageParamètres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffichageParamètres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffichageParamètres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffichageParamètres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                   
                
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel AffichageMail;
    javax.swing.JLabel AffichageNom;
    javax.swing.JLabel AffichagePrénom;
    javax.swing.JLabel AffichageStatut;
    javax.swing.JLabel AffichageVolsEffectués;
    javax.swing.JLabel AffichageÂge;
    private javax.swing.JButton BoutonEnregistrerModifParam2;
    private javax.swing.JButton BoutonRetourAffichageParamètres;
    private javax.swing.JLabel TitreAffichageParamètres;
    private javax.swing.JLabel TitreAgeAffichageParamètres;
    private javax.swing.JLabel TitreMailAffichageParamètres;
    private javax.swing.JLabel TitreMailAffichageParamètresEmployé1;
    private javax.swing.JLabel TitreNomAffichageParamètres;
    private javax.swing.JLabel TitrePrénomAffichageParamètres;
    private javax.swing.JLabel TitreStatutAffichageParamètres;
    private javax.swing.JLabel TitreVolsEffectuésAffichageParamètres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
