/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetRFL;

/**
 *
 * @author Stefan
 */
public class ChoixTypeVol extends javax.swing.JFrame {

    /**
     * Creates new form ChoixTypeVol
     */
    public ChoixTypeVol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        RetourRecherche = new javax.swing.JButton();
        TitreRechercheVol = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BoutonMenuRechercher1 = new javax.swing.JButton();
        BoutonMenuRechercher = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rechercher un vol");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        RetourRecherche.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        RetourRecherche.setForeground(new java.awt.Color(38, 70, 148));
        RetourRecherche.setText("Précédent");
        RetourRecherche.setBorder(null);
        RetourRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourRechercheActionPerformed(evt);
            }
        });

        TitreRechercheVol.setBackground(new java.awt.Color(255, 255, 255));
        TitreRechercheVol.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        TitreRechercheVol.setForeground(new java.awt.Color(38, 70, 148));
        TitreRechercheVol.setText("RECHERCHER UN VOL");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(RetourRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(TitreRechercheVol)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(RetourRecherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TitreRechercheVol, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 1120, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BoutonMenuRechercher1.setBackground(new java.awt.Color(38, 70, 148));
        BoutonMenuRechercher1.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        BoutonMenuRechercher1.setForeground(new java.awt.Color(255, 255, 255));
        BoutonMenuRechercher1.setText("Aller-Retour");
        BoutonMenuRechercher1.setBorder(null);
        BoutonMenuRechercher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMenuRechercher1ActionPerformed(evt);
            }
        });

        BoutonMenuRechercher.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        BoutonMenuRechercher.setForeground(new java.awt.Color(38, 70, 148));
        BoutonMenuRechercher.setText("Aller Simple");
        BoutonMenuRechercher.setBorder(null);
        BoutonMenuRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMenuRechercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoutonMenuRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(600, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(563, Short.MAX_VALUE)
                    .addComponent(BoutonMenuRechercher1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BoutonMenuRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BoutonMenuRechercher1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 1130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjetRFL/Template_bis.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetourRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourRechercheActionPerformed
        new MenuUtilisateur().setVisible(true);
        dispose();
    }//GEN-LAST:event_RetourRechercheActionPerformed

    private void BoutonMenuRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMenuRechercherActionPerformed
        new RechercheAllerSimple().setVisible(true);
        dispose();
    }//GEN-LAST:event_BoutonMenuRechercherActionPerformed

    private void BoutonMenuRechercher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMenuRechercher1ActionPerformed
        new RechercherAllerRetour().setVisible(true);
        dispose();
    }//GEN-LAST:event_BoutonMenuRechercher1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoixTypeVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoixTypeVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoixTypeVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoixTypeVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoixTypeVol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonMenuRechercher;
    private javax.swing.JButton BoutonMenuRechercher1;
    private javax.swing.JButton RetourRecherche;
    private javax.swing.JLabel TitreRechercheVol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
